title_block:
  coordinate: A1
  width: 14
  height: 7

theme_block:
  # theme_block is aligned to the left with title_block.
  column_position:
    type: aligned
    orientation: left
    object: title_block
  # theme_block is adjacent to the bottom of title_block.
  row_position:
    type: adjacent
    orientation: bottom
    object: title_block
  width: 10
  height: 3

schedule_block:
  column_position:
    type: aligned
    orientation: left
    object: theme_block
  row_position:
    type: adjacent
    orientation: bottom
    object: theme_block
  width: 10

rule_block:
  column_position:
    type: adjacent
    orientation: right
    object: theme_block
  row_position:
    type: adjacent
    orientation: bottom
    object: title_block
  width: 4
  height: 7

contact_block:
  column_position:
    type: aligned
    orientation: left
    object: rule_block
  row_position:
    type: adjacent
    orientation: bottom
    object: rule_block
  width: 4
  height: 9

information_block:
  column_position:
    type: aligned
    orientation: left
    object: contact_block
  row_position:
    type: aligned
    orientation: bottom
    object: schedule_block
  width: 4
  height: 22

project_block:
  column_position:
    type: aligned
    orientation: left
    object: contact_block
  row_position:
    type: adjacent
    orientation: bottom
    object: contact_block
  width: 4
  height:
    type: adjacent
    orientation: top
    object: information_block
