block_position_config: '/home/lighthouse/tm_meeting_assistant/example/jabil_jouse_template_for_print/block_position_config.yaml'
template_excel: '/home/lighthouse/tm_meeting_assistant/example/jabil_jouse_template_for_print/jabil_jouse_template_for_print.xlsx'
template_sheet_name: 'template'
template_position_sheet_name: 'template_position'
target_sheet_name: 'Sheet'
